#!/bin/sh
echo -n "Enter input: "  
read line
echo "You entered: $line" 
echo -n "Enter another line: " 
read word1 word2 word3
echo "The first word is: $word1" 
echo "The second word is: $word2"
echo "The rest of the line is: $word3" 
exit 0
