#!/bin/sh
# File Name:    ~/unix3e/BourneShell/canleave
# Author:       Syed Mansoor Sarwar
# Written:      August 18, 2004
# Modified:     May 8, 2004, Jul 29, 2014
# Purpose:      To allow a user to leave his/her terminal for a short duration
#		of time by locking the terminal after taking a code from the
#		user. Terminal is unlocked only when the user re-enters the
#		same code. Ignores command line arguments.
# Brief Description: 
#	Clear screen and turn off echo (i.e., do not display what the user
#	types at the keyboard). Take user code, save it, and ask the user
#	to re-enter his/her code just to make sure that the user remebers
#	the code that he/she has entered. It is done twice. If the user does 
#	not enter the same code, the program terminates after displaying a
#	message for the user. The user is prompted to enter the original
#	code. If the user enters the wrong code, the program keeps on
#	prompting the user until he/she enters the orginal code. The 
#	keyboard is then unlocked, echo is turned on, and program exits.

Ignore signals 1, 2, 3, 15, and 18
trap '' 1 2 3 15 18

# Clear the screen, locate the cursor at the top-left corner,
# and turn off echo 
clear
stty -echo

# Set the secret code
echo -n "Enter your code word: " 
read secretcode
echo " "

# To make sure that the user remembers the code word, 
# ask the user to enter the secrete code again.
echo -n "Enter your code word again: "
read same 
if [ $secretcode != $same ]
   then
	clear
	echo "Wrong code. Try again."
fi
echo -n "Enter your code word again: "
read same
if [ $secretcode != $same ] 
   then
	clear
	echo "Work on your short-term memory before using this code!" 
	echo "Goodbye!"
	exit 1
fi

# Keyboard locked. Hit <Enter> to continue.
clear
echo -n "Keyboard locked. Hit <Enter> to continue."
read ignore
clear

# Get user guess to unlock the terminal
clear
echo -n "Enter the code word: " 
read yourguess
echo " "

# As long as the user input is not the original code word, loop here: display
# a message and take user input again. When the user input matches the secret
# code word, terminate the loop and execute the following echo command. 
while [ "$secretcode" != "$yourguess" ]
do
   clear
   echo "Wrong code. Try again."
   echo -n "Enter the code word: "
   read yourguess
done
# Set terminal to echo mode clear
clear
echo "Back again!" 
stty echo
exit 0
